name: Deploy::Auto

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: hocgin/mysqldump
  IMAGES_HUB_USER_NAME: ${{ secrets.IMAGES_HUB_USER_NAME }}
  IMAGES_HUB_PASSWORD: ${{ secrets.IMAGES_HUB_PASSWORD }}

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
      - name: Get version from Tags
        id: prep
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=$(echo "${VERSION}" | sed 's/v//')
          echo ::set-output name=version::${VERSION}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置 Docker 编译环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 缓存 Docker 层
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # 登陆 容器镜像中心
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.IMAGES_HUB_USER_NAME }}
          password: ${{ env.IMAGES_HUB_PASSWORD }}
      # 编译和发布镜像
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.version }},${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
